// src/pages/Terms.jsx
import Header from "../components/Header";
import Footer from "../components/Footer";

export default function Terms() {
  const lastUpdated = new Date().toLocaleDateString(undefined, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <div className="min-h-screen flex flex-col bg-gray-50 text-gray-900">
      <Header />

      <main className="flex-1 px-6 py-10">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
          <p className="text-sm text-gray-500 mb-8">Last updated: {lastUpdated}</p>

          <section className="space-y-6 text-gray-800 leading-relaxed">
            <p>
              By using Guidance Goose, you agree to these terms. This is a short summary of how you
              can use the service responsibly and what you can expect in return.
            </p>

            <div>
              <h2 className="text-xl font-semibold mb-2">1. Use Responsibly</h2>
              <p>
                Guidance Goose is for personal insight and learning — not medical, legal, or
                financial advice. Always apply independent judgment before making decisions.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-2">2. Intellectual Property</h2>
              <p>
                All content, graphics, and AI personas are property of Goose Solutions. You may not
                reproduce, sell, or redistribute materials without permission.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-2">3. AI Responses</h2>
              <p>
                Responses are generated by machine learning models and may contain inaccuracies.
                The service is provided “as is” without warranty. We’re always improving accuracy,
                tone, and clarity — but final responsibility for how you use insights remains with
                you.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-2">4. Limitation of Liability</h2>
              <p>
                Goose Solutions and its contributors are not liable for decisions or outcomes based
                on Guidance Goose outputs. Use at your own discretion.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-2">5. Modifications</h2>
              <p>
                We may revise these terms periodically to reflect platform updates. Continued use of
                the app means you accept any revised terms.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-2">6. Contact</h2>
              <p>
                For questions about these terms, reach us at{" "}
                <a href="mailto:contact@guidancegoose.com" className="text-blue-700 underline">
                  contact@guidancegoose.com
                </a>.
              </p>
            </div>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
}
